name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build game
        run: ./build.sh
      - name: Upload build/
        uses: actions/upload-artifact@v3
        with:
          name: out.zip
          path: dist/out.zip
          retention-days: 30
